// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "FluidInterface.h"

FluidInterface::FluidInterface() {
  { m_win_timer = new Fl_Double_Window(1226, 675);
    m_win_timer->user_data((void*)(this));
    { m_btn_start = new Fl_Button(25, 25, 65, 40, "Start");
    } // Fl_Button* m_btn_start
    { m_btn_stop = new Fl_Button(125, 25, 65, 40, "Stop");
    } // Fl_Button* m_btn_stop
    { m_slider_one = new Fl_Slider(935, 55, 40, 450, "mySlider");
      m_slider_one->minimum(10);
      m_slider_one->maximum(200);
    } // Fl_Slider* m_slider_one
    { m_value_1 = new Fl_Value_Input(80, 80, 45, 20, "value1");
    } // Fl_Value_Input* m_value_1
    { m_value_2 = new Fl_Value_Input(80, 100, 45, 20, "value2");
    } // Fl_Value_Input* m_value_2
    { m_value_3 = new Fl_Value_Input(80, 120, 45, 20, "value3");
    } // Fl_Value_Input* m_value_3
    { m_value_5 = new Fl_Value_Input(75, 355, 45, 20, "value5");
    } // Fl_Value_Input* m_value_5
    { m_value_4 = new Fl_Value_Input(80, 140, 45, 20, "value4");
    } // Fl_Value_Input* m_value_4
    { m_table = new Fl_Table(205, 20, 610, 685);
      m_table->end();
    } // Fl_Table* m_table
    m_win_timer->end();
  } // Fl_Double_Window* m_win_timer
}
